export const actionConstants = {
  SET_AUTH: "SET_AUTH",
  GET_USERS: "GET_USERS",
  GET_BALANCE: "GET_BALANCE",
  GET_TRANSACTIONS: "GET_TRANSCTIONS",
  SET_TRANSFERRED: "SET_TRANSFERRED",
  STORE_TEMPLATE: "STORE_TEMPLATE",
  GET_TEMPLATES: "GET_TEMPLATES",
  SET_ERROR: "SET_ERROR"
};

export const transferredValues = {
  NOT_STARTED: 0,
  SUCCESS: 1,
  FAILED: 2
};
